name: audio_session
description: Sets the iOS audio session category and Android audio attributes for your app, and manages your app's audio focus, mixing and ducking behaviour.
version: 0.1.25
homepage: https://github.com/ryanheise/audio_session
topics:
  - audio
  - audio-session

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  rxdart: '>=0.26.0 <0.29.0'
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.audio_session
        pluginClass: AudioSessionPlugin
      ios:
        pluginClass: AudioSessionPlugin
      macos:
        pluginClass: AudioSessionPlugin
      web:
        pluginClass: AudioSessionWeb
        fileName: audio_session_web.dart
